#!/usr/bin/env bash

# this is too slow to do in pre-push, we call scripts/githubUploadSecrets.sh when publishing
exit 0;

# navigate to the repository root
cd "$(git rev-parse --show-toplevel)"

# run GitHup Upload Secrets script
scripts/githubUploadSecrets.sh

# check the exit status of the script
if [ $? -ne 0 ]; then
  echo "GitHub secrets upload failed, push aborted."
  exit 1
fi

echo "Secrets uploaded successfully to GitHub, proceeding with push"
exit 0
