app = 'farmaperte-staging'
primary_region = 'cdg'

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = 'stop'
# auto_stop_machines = false # activate this for cron service; then monitor VM usage to avoid costs explosion...
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

# THIS IS NOT WORKING
#[[jobs]]
#  command = ['node', 'worker.js']
#  schedule = '0 8 * * *' # every day at 8 AM o'clock

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[env]
  NODE_ENV = 'staging'
  # to avoid 'PCI: Fatal: No config space access function found' errors
  NODE_OPTIONS = '--max-old-space-size=4096'

[mounts]
  source = 'products_staging'
  destination = '/app/public/assets/products'

## Worker process (does not expose HTTP)
#[processes]
#  app = "yarn start"
#  worker = "node worker.js"

#[[machines]]
#  name = "worker"
#  count = 1

#[[machines]]
#  processes = ["worker"] # dedicate a machine for worker
#  count = 1