# fly.toml app configuration file generated for medicare-server-lingering-brook-4120 on 2024-08-24T17:23:36+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'medicare-staging'
primary_region = 'cdg'

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[env]
  NODE_ENV = 'staging'
  # to avoid "PCI: Fatal: No config space access function found" errors
  NODE_OPTIONS = '--max-old-space-size=4096'

[mounts]
  source = 'products_staging'
  destination = '/app/public/assets/products'