name: Daily Jobs

on:
  schedule:
    - cron: "*/5 * * * *" # every 5 minutes
    #- cron: "0 8 * * *"   # every day at 08:00 UTC
  workflow_dispatch:      # allow manual trigger

jobs:
  run-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Call medicare-staging job runner
        run: |
          curl -X POST "https://medicare-staging.fly.dev/api/internal/runJobs" \
            -H "x-worker-key: ${{ secrets.WORKER_KEY }}"
      # - name: Call medicare-prod job runner
      #   run: |
      #     curl -X POST "https://medicare-prod.fly.dev/api/internal/runJobs" \
      #       -H "x-worker-key: ${{ secrets.WORKER_KEY }}"